import { ANIMATIONS_BY_ID } from '../data/animations.js'
import { CATEGORY_MAP, CATEGORIES } from '../data/categories.js'
import { CONFIGURATION_STEPS } from '../data/configurationSteps.js'
import { VISUAL_THEME_MAP } from '../data/visual-foundation/themes.js'

function formatDate(value) {
  if (!value) return '—'
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString()
}

export function configurationFileName(configuration) {
  const value = `${configuration.clientName}-${configuration.configurationName}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
  return `${value || 'client-configuration'}.md`
}

export function groupConfigurationSelections(configuration) {
  return CATEGORIES.map((category) => ({
    ...category,
    selections: Object.entries(configuration.selections)
      .map(([id, selection]) => ({ animation: ANIMATIONS_BY_ID[id], selection }))
      .filter((item) => item.animation?.category === category.id)
      .sort((a, b) => a.animation.name.localeCompare(b.animation.name)),
  })).filter((category) => category.selections.length > 0)
}

export function generateConfigurationMarkdown(configuration) {
  const groups = groupConfigurationSelections(configuration)
  const selectedThemes = Object.entries(configuration.visualThemes)
    .map(([id, selection]) => ({ theme: VISUAL_THEME_MAP[id], selection }))
    .filter((item) => item.theme)
    .sort((a, b) => a.theme.name.localeCompare(b.theme.name))
  const lines = [
    '# UI Animation Configuration Report',
    '',
    `- **Client:** ${configuration.clientName}`,
    `- **Configuration:** ${configuration.configurationName}`,
    `- **Status:** ${configuration.status === 'saved' ? 'Saved / Complete' : 'Draft'}`,
    `- **Created:** ${formatDate(configuration.createdAt)}`,
    `- **Last updated:** ${formatDate(configuration.updatedAt)}`,
    `- **Completed:** ${formatDate(configuration.completedAt)}`,
  ]

  if (configuration.notes) lines.push(`- **Notes:** ${configuration.notes}`)

  lines.push('', '## Step completion', '')
  const visited = new Set(configuration.visitedSteps)
  CONFIGURATION_STEPS.forEach((step) => {
    lines.push(`- [${visited.has(step.id) ? 'x' : ' '}] ${step.label}`)
  })

  lines.push('', '## Selected animations', '')
  if (groups.length === 0) {
    lines.push('_No animations selected._', '')
  } else {
    groups.forEach((group) => {
      lines.push(`### ${group.label}`, '')
      group.selections.forEach(({ animation, selection }) => {
        const settings = selection.settings
        lines.push(`- **${animation.name}** — ${animation.description}`)
        lines.push(
          `  - Timing: ${settings.durationMs}ms duration, ${settings.delayMs}ms delay, ${settings.speed}× speed`
        )
        const contexts = configuration.usage[animation.id] ?? []
        if (contexts.length > 0) lines.push(`  - Seen in: ${contexts.join('; ')}`)
      })
      lines.push('')
    })
  }

  lines.push('## Selected visual foundations', '')
  if (selectedThemes.length === 0) {
    lines.push('_No visual foundation selected._', '')
  } else {
    selectedThemes.forEach(({ theme, selection }) => {
      lines.push(`- **${theme.name}** — ${theme.description}`)
      const overrides = Object.entries(selection.overrides ?? {})
      if (overrides.length > 0) {
        lines.push(`  - Overrides: ${overrides.map(([key, value]) => `${key}: ${value}`).join(', ')}`)
      }
    })
    lines.push('')
  }

  lines.push(
    '---',
    '',
    `Generated by UI Animation Catalogue for ${configuration.clientName}.`,
    `Category labels: ${groups.map((group) => CATEGORY_MAP[group.id]?.label).join(', ') || 'None'}.`
  )

  return lines.join('\n')
}
